# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /data

ADD https://raw.githubusercontent.com/MarkoH17/Spray365/main/requirements.txt requirements.txt
ADD https://raw.githubusercontent.com/MarkoH17/Spray365/main/spray365.py spray365.py

RUN pip3 install -r requirements.txt





